import type { Scenario, TutorialSection } from './learn-types';

export const TUTORIAL: TutorialSection[] = [
    {
        id: 'install',
        title: 'Install in one line',
        body: 'BrowserBash is a natural-language browser automation CLI: you write a plain-English objective, an AI agent drives a real Chrome browser and returns structured results. Install it globally from npm. You need Node 18 or newer and Google Chrome stable on your machine.',
        code: 'npm install -g browserbash-cli\nbrowserbash --version',
    },
    {
        id: 'first-run',
        title: 'Your first run',
        body: "Hand browserbash run an objective in plain English and watch it drive the browser. If you want a value back, end the objective with store ... as 'name' and the captured value is returned in the final state. Add --headless to hide the browser window and --timeout to cap the run in seconds.",
        code: 'browserbash run "Open https://news.ycombinator.com and store the top story title as \'top_story\'"\n\n# no visible window, give up after 90 seconds\nbrowserbash run "Open https://example.com and store the heading as \'h1\'" --headless --timeout 90',
    },
    {
        id: 'llm',
        title: 'Pick a brain: Ollama, Anthropic, or OpenRouter',
        body: 'By default BrowserBash thinks with a local Ollama model: free, open source, no API keys, just have Ollama running. Set ANTHROPIC_API_KEY and it uses Claude instead. For everything else there is OpenRouter: grab a key at openrouter.ai/keys, export OPENROUTER_API_KEY, and pass --model openrouter/<vendor>/<model>. One flag swaps between hundreds of models, so you can trade cost for capability without touching your tests.',
        code: '# Option 1 — local and free (default): just have Ollama running\nollama pull qwen3\nbrowserbash run "Open https://example.com and store the heading as \'h1\'"\n\n# Option 2 — Anthropic\nexport ANTHROPIC_API_KEY=sk-ant-...\nbrowserbash run "Open https://example.com and store the heading as \'h1\'"\n\n# Option 3 — OpenRouter: get a key at openrouter.ai/keys\nexport OPENROUTER_API_KEY=sk-or-...\nbrowserbash run "..." --model openrouter/anthropic/claude-sonnet-4-6\nbrowserbash run "..." --model openrouter/meta-llama/llama-3.3-70b-instruct',
    },
    {
        id: 'agent-mode',
        title: 'Agent mode: NDJSON + exit codes',
        body: 'The --agent flag switches stdout to NDJSON: one JSON object per line, stable schema, built for scripts and AI coding tools. Step events stream as the agent works, then a single run_end event carries the verdict, a summary, the final state with your stored values, and the duration. The process exit code is the verdict itself, so callers never have to parse output.',
        code: 'browserbash run "<objective>" --agent --headless --timeout 120\n\n# progress events, one per step\n{"type":"step","step":1,"status":"passed","action":"navigate","remark":"..."}\n\n# terminal event\n{"type":"run_end","status":"passed|failed|error|timeout","summary":"...","final_state":{...},"duration_ms":...,"test_url":"..."}\n\n# exit codes: 0 passed · 1 failed · 2 error · 3 timeout',
    },
    {
        id: 'testmd',
        title: 'Markdown test files',
        body: 'Tests are plain Markdown files ending in _test.md: committable, reviewable, and readable by anyone on the team. Each list item is one step, {{placeholders}} work everywhere, and you can splice shared steps in with @import ./helpers/login.md. Run a file with browserbash testmd run; after every run a Result.md report is written next to the test file.',
        code: "mkdir -p .browserbash/tests\ncat > .browserbash/tests/login_test.md <<'EOF'\n# Login flow\n\n- Open {{base_url}}/login\n- Type {{username}} into the email field\n- Type {{password}} into the password field and press Enter\n- Verify the dashboard heading is visible\n- Store the logged-in user name as 'user_name'\nEOF\n\nbrowserbash testmd run .browserbash/tests/login_test.md\n# -> writes .browserbash/tests/Result.md next to the test file",
    },
    {
        id: 'variables',
        title: 'Variables & secrets',
        body: 'Any {{key}} placeholder in an objective or test step gets substituted at run time. Pass values inline with --variables, from a file with --variables-file, or drop JSON files in ./.browserbash/variables/ (project) and ~/.browserbash/variables/ (global) to load them automatically. Wrap sensitive values as {"value":"...","secret":true} and they are masked as ***** in all logs and NDJSON output.',
        code: 'browserbash run "Log in to {{base_url}} as {{username}} with password {{password}}" \\\n  --variables \'{"base_url":"https://app.example.com","username":"qa@example.com","password":{"value":"hunter2","secret":true}}\'\n\n# or keep them in a file\nbrowserbash run "Log in to {{base_url}} as {{username}} with password {{password}}" \\\n  --variables-file ./staging.vars.json\n\n# secret values never leak — logs show: Type ***** into the password field',
    },
    {
        id: 'ci',
        title: 'Run it in CI',
        body: 'Agent mode and exit codes make CI integration trivial: the job fails exactly when the test fails, with zero output parsing. Run headless, set a timeout, and put your LLM key in repo secrets. Pipe the NDJSON to a file if you want step-by-step logs as a build artifact.',
        code: '# .github/workflows/e2e.yml\nname: e2e\non: [push]\njobs:\n  smoke:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm install -g browserbash-cli\n      - run: browserbash testmd run .browserbash/tests/smoke_test.md --agent --headless --timeout 180\n        env:\n          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}\n# exit code is the verdict: 0 passed · 1 failed · 2 error · 3 timeout',
    },
    {
        id: 'record',
        title: 'Record the session',
        body: 'Add --record to any run and BrowserBash captures a screenshot and a full session video — on every engine, including the free Stagehand default (the video is stitched from a CDP screencast with ffmpeg, which ships with the CLI). The builtin engine additionally captures a Playwright trace. Recordings are saved locally with the run — view them in the local dashboard (next step) or push them to your cloud dashboard with --upload.',
        code: '# record a run — screenshot + session video on any engine\nbrowserbash run "Open https://example.com and store the heading as \'h1\'" --record\n\n# the recording is saved locally; see it with: browserbash dashboard',
    },
    {
        id: 'dashboard',
        title: 'Your dashboard: local (free) or cloud (optional)',
        body: 'Every run is kept in a private on-disk store. browserbash dashboard opens a free local web dashboard — left panel of runs, main pane with the verdict, extracted values and the recording, side by side, exactly like the hosted one. Nothing leaves your machine. Want history across machines and shareable links? Create a free account at browserbash.com, connect once, and push a run with --upload. Cloud runs are kept 15 days on the free plan; Pro keeps them forever.',
        code: '# free, local, no account — opens http://localhost:4477\nbrowserbash dashboard\n\n# run and pop the local dashboard open on this run\nbrowserbash run "Open https://example.com and store the heading as \'h1\'" --record --dashboard\n\n# optional cloud: connect once, then push the runs you choose\nbrowserbash connect --key bb_...      # key from browserbash.com/dashboard\nbrowserbash run "..." --record --upload',
    },
    {
        id: 'lambdatest',
        title: 'Run on LambdaTest — every run recorded in the cloud',
        body: "Point --provider lambdatest at LambdaTest's cloud grid and the browser runs on their infrastructure instead of your machine. Every session is automatically recorded on their side: full video, network log, and browser console, all waiting in the LambdaTest Automation dashboard the moment the run ends. BrowserBash also pushes the verdict back, so each session shows up already marked passed or failed, and prints the dashboard link as test_url. One note: cloud grids use the builtin engine, which speaks the Anthropic API — set ANTHROPIC_API_KEY (Ollama and OpenRouter models stay local-only).",
        code: "# credentials: lambdatest.com -> Account Settings -> Password & Security\nexport LT_USERNAME=your_username\nexport LT_ACCESS_KEY=your_access_key\nexport ANTHROPIC_API_KEY=sk-ant-...        # cloud grids use the builtin (Anthropic) engine\n\n# or store creds once instead of env vars:\nbrowserbash login --provider lambdatest --username your_username --access-key your_access_key\n\nbrowserbash run \"Open https://www.saucedemo.com, log in as standard_user with password secret_sauce, and store the first product name as 'product'\" \\\n  --provider lambdatest\n\n# run ends with the session link:\n#   test_url: https://automation.lambdatest.com/build\n# -> open it: video replay, network log, console, and pass/fail status — recorded automatically",
    },
    {
        id: 'browserstack',
        title: 'Run on BrowserStack — video replay on Automate',
        body: "The same one flag works for BrowserStack: --provider browserstack runs your plain-English objective on BrowserStack Automate. Their dashboard keeps a video recording of the whole session plus the text and network logs, and BrowserBash reports the verdict through the browserstack_executor protocol, so the session is marked passed or failed without you touching anything. Works for single runs and full testmd files alike — your markdown tests gain cloud video replay with zero changes to the test.",
        code: "# credentials: browserstack.com -> Account & Profile -> Summary (Automate section)\nexport BROWSERSTACK_USERNAME=your_username\nexport BROWSERSTACK_ACCESS_KEY=your_access_key\nexport ANTHROPIC_API_KEY=sk-ant-...        # cloud grids use the builtin (Anthropic) engine\n\n# or: browserbash login --provider browserstack --username ... --access-key ...\n\n# single run on the grid\nbrowserbash run \"Open https://news.ycombinator.com and store the top story title as 'top_story'\" \\\n  --provider browserstack\n\n# whole markdown test file on the grid — same file, just add the flag\nbrowserbash testmd run .browserbash/tests/login_test.md --provider browserstack\n\n# test_url: https://automate.browserstack.com/dashboard\n# -> video replay + logs per session, already marked passed/failed",
    },
];

export const SCENARIOS: Scenario[] = [
    // ---- beginner ----
    {
        id: 'hello-browser',
        title: 'Hello, Browser',
        difficulty: 'beginner',
        category: 'extraction',
        targetUrl: 'https://example.com',
        objective: "Open https://example.com and store the main heading text as 'h1'",
        command: 'browserbash run "Open https://example.com and store the main heading text as \'h1\'" --headless',
        hints: [
            'The simplest possible run — one page, one extraction.',
            "Anything phrased as store ... as 'name' lands in final_state.",
        ],
        expected: "Run passes with final_state {\"h1\": \"Example Domain\"} and exit code 0.",
        learns: 'The core loop: objective in, verdict and extracted values out.',
    },
    {
        id: 'front-page-news',
        title: 'Front Page News',
        difficulty: 'beginner',
        category: 'extraction',
        targetUrl: 'https://news.ycombinator.com',
        objective: "Open https://news.ycombinator.com and store the top story title as 'top_story' and its points as 'points'",
        command: 'browserbash run "Open https://news.ycombinator.com and store the top story title as \'top_story\' and its points as \'points\'" --headless',
        hints: [
            'One objective can store multiple values — just name each one.',
            'Points live in the subtext row under each story title.',
        ],
        expected: 'Run passes with two keys in final_state: top_story and points.',
        learns: 'Extracting multiple values from one page in a single pass.',
    },
    {
        id: 'quote-quality-control',
        title: 'Quote Quality Control',
        difficulty: 'beginner',
        category: 'verification',
        targetUrl: 'https://quotes.toscrape.com',
        objective: "Open https://quotes.toscrape.com, verify there are exactly 10 quotes on the first page, and store the first quote's author as 'author'",
        command: 'browserbash run "Open https://quotes.toscrape.com, verify there are exactly 10 quotes on the first page, and store the first quote\'s author as \'author\'" --headless',
        hints: [
            'Objectives can mix assertions ("verify ...") with extraction.',
            'If a verify step is false, the run fails with exit code 1 — that is the point.',
        ],
        expected: "Run passes with final_state {\"author\": \"Albert Einstein\"}.",
        learns: 'Mixing verification and extraction — your first real test.',
    },
    {
        id: 'judge-a-book',
        title: 'Judge a Book by Its Cover',
        difficulty: 'beginner',
        category: 'extraction',
        targetUrl: 'https://books.toscrape.com',
        objective: "Open https://books.toscrape.com and store the title and price of the first book as 'title' and 'price'",
        command: 'browserbash run "Open https://books.toscrape.com and store the title and price of the first book as \'title\' and \'price\'" --headless',
        hints: [
            'books.toscrape.com is a sandbox built for scraping practice.',
            'Prices include the £ sign — the agent stores what it sees.',
        ],
        expected: 'Run passes; final_state holds the first book title (A Light in the Attic) and its price.',
        learns: 'Targeting a specific element among many similar ones.',
    },

    // ---- intermediate ----
    {
        id: 'secret-agent-login',
        title: 'Secret Agent Login',
        difficulty: 'intermediate',
        category: 'login',
        targetUrl: 'https://the-internet.herokuapp.com/login',
        objective: "Open {{base_url}}/login, log in as {{username}} with password {{password}}, and verify the page says 'You logged into a secure area'",
        command: 'browserbash run "Open {{base_url}}/login, log in as {{username}} with password {{password}}, and verify the page says \'You logged into a secure area\'" --headless --variables \'{"base_url":"https://the-internet.herokuapp.com","username":"tomsmith","password":{"value":"SuperSecretPassword!","secret":true}}\'',
        hints: [
            'The demo credentials are printed right on the login page.',
            'Mark the password {"value":"...","secret":true} — then grep your logs for it. You will find *****.',
        ],
        expected: 'Run passes, and every log line shows the password masked as *****.',
        learns: 'Variables, secret masking, and a real login flow.',
    },
    {
        id: 'supermarket-sweep',
        title: 'Supermarket Sweep',
        difficulty: 'intermediate',
        category: 'e2e',
        targetUrl: 'https://www.saucedemo.com',
        objective: "Open {{base_url}}, log in as {{username}} with password {{password}}, add the Sauce Labs Backpack to the cart, and store the cart badge count as 'cart_count'",
        command: 'browserbash run "Open {{base_url}}, log in as {{username}} with password {{password}}, add the Sauce Labs Backpack to the cart, and store the cart badge count as \'cart_count\'" --headless --variables \'{"base_url":"https://www.saucedemo.com","username":"standard_user","password":{"value":"secret_sauce","secret":true}}\'',
        hints: [
            'saucedemo.com is Sauce Labs’ public practice shop — standard_user / secret_sauce.',
            'The cart badge is the little number on the cart icon, top right.',
        ],
        expected: "Run passes with final_state {\"cart_count\": \"1\"}.",
        learns: 'A multi-step shop flow: login, action, then state extraction.',
    },
    {
        id: 'form-and-function',
        title: 'Form and Function',
        difficulty: 'intermediate',
        category: 'forms',
        targetUrl: 'https://httpbin.org/forms/post',
        objective: "Open https://httpbin.org/forms/post, fill the customer name with 'Bo Basher', choose a Large pizza, check the cheese topping, submit the form, and verify the response contains 'Bo Basher'",
        command: 'browserbash run "Open https://httpbin.org/forms/post, fill the customer name with \'Bo Basher\', choose a Large pizza, check the cheese topping, submit the form, and verify the response contains \'Bo Basher\'" --headless',
        hints: [
            'Radio buttons, checkboxes and text inputs — all in plain English.',
            'httpbin echoes the submitted form back as JSON, perfect for verification.',
        ],
        expected: 'Run passes after the submitted JSON echo shows custname "Bo Basher".',
        learns: 'Form controls: text, radio, checkbox, submit — no selectors needed.',
    },
    {
        id: 'search-party',
        title: 'Search Party',
        difficulty: 'intermediate',
        category: 'search',
        targetUrl: 'https://duckduckgo.com',
        objective: "Open https://duckduckgo.com, search for 'browser automation', and store the title of the first result as 'first_result'",
        command: 'browserbash run "Open https://duckduckgo.com, search for \'browser automation\', and store the title of the first result as \'first_result\'" --headless --timeout 120',
        hints: [
            'Search pages re-render after submit — the agent snapshots again automatically.',
            'Results vary day to day; assert on storing a value, not on a specific title.',
        ],
        expected: 'Run passes with a non-empty first_result in final_state.',
        learns: 'Handling navigation triggered by a search, plus dynamic content.',
    },

    // ---- advanced ----
    {
        id: 'checkout-champion',
        title: 'Checkout Champion',
        difficulty: 'advanced',
        category: 'e2e',
        targetUrl: 'https://www.saucedemo.com',
        objective: "Open {{base_url}}, log in as {{username}} with password {{password}}, add the Sauce Labs Backpack and Sauce Labs Bike Light to the cart, go to checkout, fill first name 'Bo', last name 'Basher', postal code '94016', finish the order, and store the confirmation header as 'confirmation'",
        command: 'browserbash run "Open {{base_url}}, log in as {{username}} with password {{password}}, add the Sauce Labs Backpack and Sauce Labs Bike Light to the cart, go to checkout, fill first name \'Bo\', last name \'Basher\', postal code \'94016\', finish the order, and store the confirmation header as \'confirmation\'" --headless --timeout 180 --max-steps 40 --variables \'{"base_url":"https://www.saucedemo.com","username":"standard_user","password":{"value":"secret_sauce","secret":true}}\'',
        hints: [
            'Long flows need headroom: raise --timeout and --max-steps.',
            'The agent handles cart → checkout → overview → finish as separate steps.',
        ],
        expected: "Run passes with final_state {\"confirmation\": \"Thank you for your order!\"}.",
        learns: 'A full e2e purchase: 10+ steps, one English sentence.',
    },
    {
        id: 'dropdown-dexterity',
        title: 'Dropdown Dexterity',
        difficulty: 'advanced',
        category: 'interactions',
        targetUrl: 'https://the-internet.herokuapp.com/dropdown',
        objective: "Open {{base_url}}/dropdown, select 'Option 2' from the dropdown, then open {{base_url}}/checkboxes, check both checkboxes, and verify both are checked",
        command: 'browserbash run "Open {{base_url}}/dropdown, select \'Option 2\' from the dropdown, then open {{base_url}}/checkboxes, check both checkboxes, and verify both are checked" --headless --variables \'{"base_url":"https://the-internet.herokuapp.com"}\'',
        hints: [
            'One objective can span multiple pages — just chain the steps.',
            'Checkbox 2 starts checked; the agent must notice and leave it alone.',
        ],
        expected: 'Run passes after both interactions verify cleanly.',
        learns: 'Native form widgets across multiple pages in one run.',
    },
    {
        id: 'price-patrol',
        title: 'Price Patrol',
        difficulty: 'advanced',
        category: 'extraction',
        targetUrl: 'https://books.toscrape.com',
        objective: "Open https://books.toscrape.com, navigate to the Travel category, store the number of books shown as 'count' and the price of the most expensive book on the page as 'max_price'",
        command: 'browserbash run "Open https://books.toscrape.com, navigate to the Travel category, store the number of books shown as \'count\' and the price of the most expensive book on the page as \'max_price\'" --headless --timeout 120',
        hints: [
            'The category list is in the left sidebar.',
            'Finding a maximum means the agent has to read every price — give it time.',
        ],
        expected: "Run passes with count \"11\" and the highest price on the Travel page.",
        learns: 'Navigation plus comparative reasoning over page data.',
    },
    {
        id: 'markdown-test-drive',
        title: 'Markdown Test Drive',
        difficulty: 'advanced',
        category: 'testing',
        targetUrl: 'https://news.ycombinator.com',
        objective: 'Write a committable *_test.md file and run it with testmd — your first reviewable test artifact',
        command: "cat > hn_test.md <<'EOF'\n# Hacker News smoke\n\n- Open https://news.ycombinator.com\n- Verify the page has loaded and stories are visible\n- Store the title of the first story as 'top_story'\n- Store the points of the first story as 'top_points'\nEOF\nbrowserbash testmd run ./hn_test.md --headless",
        hints: [
            'Each markdown list item becomes one verified step.',
            'After the run, open Result.md — it is written next to the test file.',
            'Share steps between tests with @import ./helpers/login.md.',
        ],
        expected: 'Exit code 0 and a Result.md containing the verdict plus both extracted values.',
        learns: 'Tests as reviewable markdown files your whole team can read.',
    },
    {
        id: 'lambdatest-replay',
        title: 'Cloud Replay: LambdaTest',
        difficulty: 'advanced',
        category: 'cloud',
        targetUrl: 'https://www.saucedemo.com',
        objective: "Run the SauceDemo cart flow on LambdaTest's grid and watch the full video replay in their Automation dashboard",
        command: 'export LT_USERNAME=your_username\nexport LT_ACCESS_KEY=your_access_key\nexport ANTHROPIC_API_KEY=sk-ant-...\n\nbrowserbash run "Open https://www.saucedemo.com, log in as standard_user with password secret_sauce, add the Sauce Labs Backpack to the cart, and store the cart badge count as \'cart_count\'" --provider lambdatest --name "saucedemo cart"',
        hints: [
            'No --headless needed — the browser lives on their grid, not your machine.',
            'The --name flag becomes the test name in the LambdaTest dashboard.',
            'Cloud grids use the builtin engine, so ANTHROPIC_API_KEY is required.',
        ],
        expected: "Run passes with cart_count \"1\"; automation.lambdatest.com shows the session marked passed with full video, network log, and console.",
        learns: 'Cloud execution: every run auto-recorded with video, no local browser.',
    },
    {
        id: 'browserstack-replay',
        title: 'Cloud Replay: BrowserStack',
        difficulty: 'advanced',
        category: 'cloud',
        targetUrl: 'https://the-internet.herokuapp.com/login',
        objective: 'Run a markdown test file on BrowserStack Automate and get a video replay of every step, marked passed or failed',
        command: "cat > grid_login_test.md <<'EOF'\n# Secure area login (on the grid)\n\n- Open https://the-internet.herokuapp.com/login\n- Log in as tomsmith with password SuperSecretPassword!\n- Verify the page says 'You logged into a secure area'\nEOF\n\nexport BROWSERSTACK_USERNAME=your_username\nexport BROWSERSTACK_ACCESS_KEY=your_access_key\nexport ANTHROPIC_API_KEY=sk-ant-...\n\nbrowserbash testmd run ./grid_login_test.md --provider browserstack",
        hints: [
            'Same markdown file runs locally or on the grid — only the flag changes.',
            'BrowserBash reports the verdict via the browserstack_executor protocol, so Automate shows passed/failed automatically.',
            'The session video and logs land at automate.browserstack.com the moment the run ends.',
        ],
        expected: 'Exit code 0, Result.md written locally, and a BrowserStack Automate session marked passed with video replay.',
        learns: 'The same reviewable test file, now with cloud video evidence per run.',
    },
];
